$("#editor").trumbowyg({
    urlProtocol: !0,
    minimalLinks: !0,
    autogrow: !0,
    changeActiveDropdownIcon: !0,
    semantic: !0,
    removeformatPasted: !0,
    autogrowOnEnter: !0,
    btnsDef: {
        align: {
            dropdown: ["justifyLeft", "justifyCenter", "justifyRight", "justifyFull"],
            ico: "justifyLeft"
        }
    },
    btns: [
        ["fontsize"],
        ["align"],
        ["strong", "em", "underline"],
        ["link"],
        ["unorderedList", "orderedList"],
        ["removeformat"],
        ["viewHTML"],
        ["fullscreen"]
    ],
    plugins: {
        fontsize: {
            sizeList: ["12px", "14px", "16px"]
        }
    }
});


$("#editor").trumbowyg("html"), $("#editor").trumbowyg("html", '<h1 style="text-align:center;">Shipping Policy</h1><br><p style="text-align:center;"><strong> LAST MODIFIED: <span id="date"></span></strong></p><br><br><p><strong class="website_name company_name"><span class="dashed">Termzy LLC</span></strong>, referred to as "we" and "us", operates the website (<a href="https://termzy.io" class="website_url"><span class="dashed">termzy.io</span></a>) referred to as the "Website". When you place an order through this Website, you accept the following terms. These terms are established to ensure mutual understanding and agreement between both parties regarding our services and to protect the interests of both parties.</p><br><h4>1. General</h4><p>Subject to stock availability, we make an effort to keep accurate stock numbers on our website. However, on occasion, there may be an error in our stock count, leading to a situation where we cannot fulfill all your items at the time of purchase. If this occurs, we will deliver the available products to you and get in touch with you to determine if you prefer to wait for the restocked item or receive a refund.</p><br><h4>2. Shipping Costs</h4><p>The shipping fee is calculated during the checkout process, based on the weight, dimensions, and delivery location of the items in the order. The shipping payment will be added to the overall purchase amount and will serve as the final cost for the customer.<p><br><h4>3. Returns</h4><h5>3.1 Return Due To Change Of Mind</h5><p>At <span class="website_name company_name"><span class="dashed">Termzy LLC</span></span>, we are more than happy to accommodate returns based on a change of mind, provided that the request for return is received by us within <strong class="days-return"><span class="dashed">5</span></strong> days of receipt of the item.</p><p>The item must be returned in its original packaging, unopened and in a condition that is suitable for resale.</p><p>The customer will be responsible for paying for the return shipping and must arrange for the shipping themselves.</p><p>Once the return is received and accepted, we will process a refund in the form of store credit for a future purchase. Generated by <a href="https://termzy.io" style="text-decoration:none;color:black;cursor:auto;">Termzy.io</a>. We will notify you via email once the process is completed.</p><p>Please note that while we will refund the value of the returned goods, we will not refund the shipping costs that were originally paid by the customer.</p><h5>3.2 Warranty Returns</h5><p><span class="website_name company_name"><span class="dashed">Termzy LLC</span></span> is committed to fulfilling all legitimate warranty claims, but they must be submitted within 90 days of receiving the items.</p><p>To facilitate the return process, customers will need to pay for the shipping upfront, but <span class="website_name company_name"><span class="dashed"><span class="website_name company_name"><span class="dashed">Termzy LLC</span></span></span></span> will reimburse the cost upon a successful warranty claim.</p><p>Once <span class="website_name company_name"><span class="dashed">Termzy LLC</span></span> receives the returned items for a warranty claim, they aim to process it within 7 days.</p><ul>Upon confirming your warranty claim, you will have the option to choose from:<li>A reimbursement to the payment method used;</li><li>An in-store credit refund;</li><li>Receiving a new item (if stock is readily available).</li></ul><br><h4>4. Delivery Terms</h4><h5>4.1 Transit Time Domestically</h5><p>Typically, it takes 2 to 7 days for domestic shipments to be delivered.</p><h5>4.2 Transit time Internationally</h5><p>International shipping typically takes between 4 to 22 days in transit, with the exact duration dependent on the courier chosen. An accurate estimate can be provided during the checkout process when selecting the courier.</p><h5>4.3 Dispatch time</h5><div class="dispatch-time"></div><p>The warehouse operates from Monday to Friday during standard business hours, except on national holidays when it is closed. During these holidays, measures are taken to minimize shipment delays.</p><h5>4.4 Change Of Delivery Address</h5><p>Regarding requests for changing the delivery address, we can alter it prior to the dispatch of the order.</p><h5>4.5 P.O. Box Shipping</h5><p><span class="website_name company_name"><span class="dashed">Termzy LLC</span></span> will only use postal services for delivering to P.O. box addresses. Courier services are not available for these types of addresses.</p><h5>4.6 Military Address Shipping</h5><p>The shipping of packages to military addresses is possible with USPS, however, courier services do not offer this service.</p><h5>4.7 Items Out Of Stock</h5><div class="out-stock"></div><p>In the event of an item being unavailable, we will process a cancellation and refund for the out-of-stock item and proceed with shipping the remaining items in the order.</p><h5>4.8 Delivery Time Exceeded</h5><p>Please contact us if the delivery time has surpassed the expected delivery window, so we can initiate an inquiry.</p><br><h4>5. Tracking Notifications</h4><p>Once their order is dispatched, customers will receive a tracking link which will allow them to monitor the status of their shipment, as updated by the shipping provider.</p><br><h4>6. Parcels Damaged In Transit</h4><p>In the event of a damaged parcel during transit, kindly reject it from the courier if possible and reach out to our customer service team. If the parcel was delivered in your absence, please inform our customer service team for further instructions.</p><br><h4>7. Duties & Taxes</h4><h5>7.1 Sales Tax</h5><p>Sales tax has already been applied to the price of the goods as displayed on the website.</p><h5>7.2 Import Duties & Taxes</h5><div class="duties"></div><br><h4>8. Cancellations</h4><p>You may cancel your order at any time prior to dispatch. However, if your order has already been dispatched, kindly refer to our refund policy for further information.</p><br><h4>9. Insurance</h4><p>The insurance coverage for loss and damage of parcels is up to the value declared by the courier.</p><h5>9.1 Process for parcel damaged in-transit</h5><p>We will process a refund or replacement as soon as the courier has completed their investigation into the claim.</p><h5>9.2 Process for parcel lost in-transit</h5><p>As soon as the courier finishes investigating the claim, we will proceed with either a refund or a replacement.</p><br><h4>10. Customer service</h4><p class="email-text"></p><p class="phone-text"></p>');

var a1 = "Orders that are submitted prior to 4 PM (UTC-05) will be shipped out on the same day, otherwise, they will be processed and sent out during the following business day.",
    a2 = "Orders are typically sent out within 2 working days after payment has been received.",
    a3 = "Your order will not be dispatched until the out-of-stock item becomes available. In the meantime, the other items in your order will be kept on hold.",
    a4 = "In case an item is not available, we will promptly send the available items and will send the rest of them as soon as they are back in stock.",
    a5 = "In the event of an item being unavailable, we will process a cancellation and refund for the out-of-stock item and proceed with shipping the remaining items in the order.",
    a6 = "<p>International shipments may be subject to import duties and taxes upon arrival in the destination country. These fees vary by country, and we advise you to familiarize yourself with these potential costs prior to placing an order with us.</p><p>If you decline to pay duties and taxes upon reaching your destination country, the merchandise will be shipped back at your expense. You will receive a reimbursement for the amount paid for the goods, minus the cost of the return shipment. The initial shipping fee will not be included in the refund.</p>",
    a7 = "The customs duties and taxes for international deliveries will be taken care of ahead of time, without requiring the customer to pay any additional charges when the shipment reaches its destination country.",
    a8 = "<p>For international deliveries, there may be import duties and taxes that need to be paid. Email will pre-calculate these fees and present them during checkout, offering customers the option to either pay for them upfront or pay separately upon arrival in the destination country. Email strongly suggests pre-paying duties and taxes as it speeds up the delivery process and reduces the risk of delays at customs.</p><p>If a customer chooses not to pay duties and taxes upon arrival, the goods will be returned to email at the customer&apos;s expense. The customer will receive a refund for the product value, minus the cost of the return shipping. The cost of the initial shipping will not be refunded.</p>",
    a9 = 'You can reach us during our working hours by calling: <a class="phone-number" href="tel:+1234567890">+1234567890</a>.',
    a10 = 'For all customer service enquiries, please email us at <a href="mailto:contact@termzy.io" class="website_email">contact@termzy.io</a>.';


$("#website-name").keyup(function() {
    $(".website_name").html(this.value), $(".company_name").html(this.value)
}), $("#company-name").keyup(function() {
    $(".company_name").html(this.value)
}), $("#company-country").keyup(function() {
    $(".company_country").html(this.value)
}), $("#website-email").keyup(function() {
    $(".website_email").html(this.value)
}), $("#days-return").keyup(function() {
    $(".days-return").html(this.value)
}), $("#website-url").keyup(function() {
    let e = this.value.replace(/https?:\/\//i, "");
    $(".website_url").html(e), $(".website_url").prop("href", "https://" + e)
});




document.addEventListener("DOMContentLoaded", function(e) {
    var t = new Date;
    t.setDate(t.getDate()), $("#date").html(t.getDate() + " " + ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"][t.getMonth()] + " " + t.getFullYear());
    var a = window.location.protocol + "//" + window.location.hostname + window.location.pathname;
    $(".termzy a").attr("href", a)
});



function CopyToClipboard(e) {
    var t, o, a = document,
        n = a.getElementById(e);
    a.body.createTextRange ? ((t = a.body.createTextRange()).moveToElementText(n), t.select(), t.mouseup()) : window.getSelection && (o = window.getSelection(), (t = a.createRange()).selectNodeContents(n), o.removeAllRanges(), o.addRange(t)), document.execCommand("copy"), document.getElementById("copy-button").value = "Copied"
}
const toastTrigger = document.getElementById("copy-button"),
    toastLiveExample = document.getElementById("liveToast");
toastTrigger && toastTrigger.addEventListener("click", () => {
    let e = new bootstrap.Toast(toastLiveExample);
    e.show(), $("#editor").addClass("overlay").delay(2500).queue(function() {
        $(this).removeClass("overlay"), $(this).dequeue()
    }), $(".progress-bar").animate({
        width: "100%"
    }, 500), $(".copying").delay(1e3).queue(function() {
        $(this).html("Done ✔️")
    })
});



document.addEventListener("DOMContentLoaded", function(e) {
    $("#same-day-dispatch-yes").change(function() {
        $(this).attr("id");
        var e = a1,
            a = "same-day-dispatch-yes";
        $(this).is(":checked") ? $(".dispatch-time").append("<p class='" + a + "'>" + e + "</p>") : $("." + a).remove()
    }), $("#same-day-dispatch-no").change(function() {
        $(this).attr("id");
        var e = a2,
            a = "same-day-dispatch-no";
        $(this).is(":checked") ? $(".dispatch-time").append("<p class='" + a + "'>" + e + "</p>") : $("." + a).remove()
    }), $("#available-stock").change(function() {
        $(this).attr("id");
        var e = a3,
            a = "available-stock";
        $(this).is(":checked") ? $(".out-stock").append("<p class='" + a + "'>" + e + "</p>") : $("." + a).remove()
    }), $("#partial-stock").change(function() {
        $(this).attr("id");
        var e = a4,
            a = "partial-stock";
        $(this).is(":checked") ? $(".out-stock").append("<p class='" + a + "'>" + e + "</p>") : $("." + a).remove()
    }), $("#all-stock").change(function() {
        $(this).attr("id");
        var e = a5,
            a = "all-stock";
        $(this).is(":checked") ? $(".out-stock").append("<p class='" + a + "'>" + e + "</p>") : $("." + a).remove()
    }), $("#on-arrival").change(function() {
        $(this).attr("id");
        var e = a6,
            a = "on-arrival";
        $(this).is(":checked") ? $(".duties").append("<span class='" + a + "'>" + e + "</span>") : $("." + a).remove()
    }), $("#price-included").change(function() {
        $(this).attr("id");
        var e = a7,
            a = "price-included";
        $(this).is(":checked") ? $(".duties").append("<p class='" + a + "'>" + e + "</p>") : $("." + a).remove()
    }), $("#customer-choose").change(function() {
        $(this).attr("id");
        var e = a8,
            a = "customer-choose";
        $(this).is(":checked") ? $(".duties").append("<span class='" + a + "'>" + e + "</span>") : $("." + a).remove()
    }), $("#phone").change(function() {
        $(this).attr("id");
        var e = a9,
            a = "phone";
        $(this).is(":checked") ? ($(".phone-text").append("<p class='" + a + "'>" + e + "</p>"), $(".number").removeClass("d-none"), $("#phone-input").keyup(function() {
            $(".phone-number").attr("href", "tel:" + this.value), $(".phone-number").html(this.value)
        })) : ($("." + a).remove(), $(".number").addClass("d-none"))
    }), $("#email").change(function() {
        $(this).attr("id");
        var e = a10,
            a = "email";
        $(this).is(":checked") ? ($(".email-text").append("<p class='" + a + "'>" + e + "</p>"), $(".mail").removeClass("d-none"), $("#email-input").keyup(function() {
            $(".website_email").attr("href", "mailto:" + this.value), $(".website_email").html(this.value)
        })) : ($("." + a).remove(), $(".mail").addClass("d-none"))
    })
});
